### ISSUE TITLE
Attachment Module

### ISSUE THREAD

**Issue by Anisa-Nur** [ov-sa/vRPZ-Framework#13]
Module isn't accounting for entity's rotation. Also add a property to pass rotation relative to the object rotation.

**Comment by Aviril** [comment]
> Module isn't accounting for entity's rotation. Also add a property to pass rotation relative to the object rotation.
I've fixed this already in Yesterday's release.

**Comment by Aviril** [comment]
> Also add a property to pass rotation relative to the object rotation.
However, this needs to be done

**Comment by Anisa-Nur** [comment]
Resolved. Added `isRelative` to rotation property for attachment API. https://github.com/ov-sa/Assetify-Library/wiki/Module:-Bone-Attachments#-how-to-setup-bone-attachments
