### ISSUE TITLE
Fix Character's Head

### ISSUE THREAD

**Issue by Anisa-Nur** [ov-sa/vRPZ-Framework#18]
Delete these polygons from every clump: ![](https://cdn.discordapp.com/attachments/765010434884763700/967120964615798844/gta_sa_2022-04-22_20-49-49-59.png)

**Comment by Aviril** [comment]
Fixed & Upated all clumps.
![image](https://user-images.githubusercontent.com/89867985/164793579-e2391e7e-27a1-4425-bd1b-51f196ee960d.png)
