### ISSUE TITLE
Improve `assetDeps` in Assetify

### ISSUE THREAD

**Issue by Anisa-Nur** [ov-sa/vRPZ-Framework#24]
Let there be categories of deps and selective categories will be having special function. For example: 
```lua
{
    "assetDeps": [
        "texture": {
            "inventory_icon": "icon/inventory.png",
            "hud_icon": "icon/hud.png"
        }
    ]
}
```
`texture` deps will be retrieved as texture element when dependency is retrieved via API.

**API proposal syntax:**
```lua
local cFile = assetify.fetchDep(assetType, assetName, depType, depIndex)
```

**Comment by Aviril** [comment]
> Let there be categories of deps and selective categories will be having special function. For example:
> 
> ```lua
> {
>     "assetDeps": [
>         "texture": {
>             "inventory_icon": "icon/inventory.png",
>             "hud_icon": "icon/hud.png"
>         }
>     ]
> }
> ```
> 
> `texture` deps will be retrieved as texture element when dependency is retrieved via API.
> 
> **API proposal syntax:**
> 
> ```lua
> local cFile = assetify.fetchDep(assetType, assetName, depType, depIndex)
> ```

Implemented the proposal. Kindly refer: https://github.com/ov-sa/Assetify-Library/wiki/Module:-APIs#-assetifygetassetdep-client
