### ISSUE TITLE
Hud image files loss

### ISSUE THREAD

**Issue by walidza** [ov-sa/vRPZ-Framework#26]
in file [`player_handler\handlers\hud` ](https://github.com/ov-sa/vRPZ-Framework/blob/main/%5BHandler%5D/player_handler/handlers/hud/player.lua)
line [58 ](https://github.com/ov-sa/vRPZ-Framework/blob/main/%5BHandler%5D/player_handler/handlers/hud/player.lua#:~:text=bgTexture%20%3D%20imports.beautify.native.createTexture(%22files/images/hud/status/slotBG1.png%22%2C%20%22dxt5%22%2C%20true%2C%20%22clamp%22)%2C), [70 ](https://github.com/ov-sa/vRPZ-Framework/blob/main/%5BHandler%5D/player_handler/handlers/hud/player.lua#:~:text=bgTexture%20%3D%20imports.beautify.native.createTexture(%22files/images/hud/status/slotBG2.png%22%2C%20%22dxt5%22%2C%20true%2C%20%22clamp%22)%2C)can't find background texture image slot **slotBG1.png** and **slotBG2.png**

**Comment by OvileAmriam** [comment]
This isn't lost these are just temporary files which will be removed anyway, thats why we haven't pushed it. Its just showing the error once while the `player_handler` starts wont be showing anymore thereafter.

**Comment by OvileAmriam** [comment]
We already have inventory icons which we will convert to whitish hud image via instead of separate textures per weapon to avoid memory flooding

**Comment by OvileAmriam** [comment]
@Aviril @Anisa-Nur

**Comment by Aviril** [comment]
These are temporary files (for debugging hud position) which only produces error when the resource is started, those files will be removed anyway when I integrate inventory icons w/ HUD.
However, Thanks for your concern.
