### ISSUE TITLE
Survival Time Issue

### ISSUE THREAD

**Issue by OvileAmriam** [ov-sa/vRPZ-Framework#29]
Survival-Time doesn't gets resetted when the player is wasted. It should get resetted to 0.

**Comment by Anisa-Nur** [comment]
**Patched:** https://github.com/ov-sa/vRPZ-Framework/blob/main/%5BLibrary%5D/assetify_library/files/assets/module/vRPZ_Config/dep/gameplay/spawns.lua#L12
