### ISSUE TITLE
Hair Floating

### ISSUE THREAD

**Issue by Anisa-Nur** [ov-sa/vRPZ-Framework#6]
One of the Hair model is floating abit (Either of Survival, Generic).

**Comment by thejdmego** [comment]
Can you provide more info about it? Name of the model, clumping, etc

**Comment by Anisa-Nur** [comment]
> Can you provide more info about it? Name of the model, clumping, etc

Yes https://github.com/ov-sa/vRPZ-Framework/tree/main/%5BLibrary%5D/assetify_library/files/assets/character/vRPZ_Male/clump
All clump models starting from "H1XXXX" and "H2XXXX" needs to be examined. Its mostly "H2XXXX" the bugged one.

**Comment by Aviril** [comment]
Fixed floating issue. Added higher poly arms + fingers, 
![image](https://user-images.githubusercontent.com/89867985/164763978-74d7305e-bcbf-494a-96a7-6a16fa4727ab.png)
